name: Build and Publish

on:
  pull_request:
    paths: &paths
      - '.github/workflows/BuildPublish.yml'
      - 'Project.toml'
      - 'custom.scss'
      - '_quarto.yml'
      - '**/index.qmd'
      - 'paralleltestrunner/demo/**'
      - '_extensions/**'
  push:
    branches:
      - main
    paths: *paths
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: all builds except for builds on the `main` branch
  # Cancel intermediate builds: only pull request builds
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build-publish:
    timeout-minutes: 20

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - uses: julia-actions/install-juliaup@v3.1.5
      with:
        channel: '1.12'

    - name: Load Julia packages from cache
      uses: julia-actions/cache@v3

    - name: Install dependencies
      shell: julia --color=yes --project {0}
      run: |
        using Pkg: Pkg
        Pkg.instantiate()

    - name: Render project
      shell: julia --color=yes --project {0}
      run: |
        using quarto_jll: quarto
        run(`$(quarto()) render`)

    - name: Configure Git
      if: github.event_name != 'pull_request'
      run: |
        git config user.name "${{github.actor}}"
        git config user.email "${{github.actor_id}}+${{github.actor}}@users.noreply.github.com"

    - name: Publish presentation
      shell: julia --color=yes --project {0}
      if: github.event_name != 'pull_request'
      run: |
        using quarto_jll: quarto
        run(`$(quarto()) publish --no-render --no-prompt --no-browser gh-pages`)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload rendered website as an artefact
      uses: actions/upload-artifact@v7
      with:
        name: build
        path: _site
        retention-days: 7
